name: Docker

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.event.repository.name | lower }}
          tags: latest
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Command SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASSWORD }}
          script: |
            cd /var/www/vhosts/jperret.dev
            docker compose down && docker image rm ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name | lower }}:latest && docker compose up -d
