name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ${{ secrets.REGISTRY_HOST }}
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ github.event.repository.name }}
          tags: latest
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: appleboy/ssh-action@v0.1.10
        name: Command SSH
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/vhosts/jperret.dev
            docker compose down && docker image rm ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}:latest && docker compose up -d